### PR TITLE
fix: error in loading through json

### PR DESCRIPTION
**Pull request by Lethe10137**
## Description

The latest version of netem-trace was found to failed to load a trace from such `test.json` file:

```json
{"TraceBwConfig":[["1ms",["2Mbps","3Mbps"]],["2ms",["5Mbps","8Mbps"]]]}
```
it gives 
```
"invalid type: found string \"25ms\", expected a borrowed string in test_trace.json
```

## How Has This Been Tested

It has been test locally with the following code, and ran well.
```rust
    let trace: Box<dyn BwTraceConfig> = Figment::new()
        .merge(Json::file("test_trace.json"))
        .extract()
        .unwrap();

    let mut model = trace.into_model();

```

## Checklist

- [x] Code follows the code style of this project.
- [x] Changes follow the **CONTRIBUTING** guidelines.
- [x] Update necessary documentation accordingly.
- [x] Lint and tests pass locally with the changes.
- [x] Check issues and pull requests first. You don't want to duplicate effort.

### CODE REVIEW

**Comment by BobAnkh** [comment]
@Lethe10137 Can you also add some tests (if they don't already exist) for serialization/deserialization to check for this kind of bug?

**Comment by Lethe10137** [comment]
[21346c3](https://github.com/stack-rs/netem-trace/pull/15/commits/21346c36287cbac6c026ab821bd07193a5f462f8) is intended to fail

**Review by BobAnkh — CHANGES_REQUESTED** [review]
Please use `serde_json` directly for our tests instead of introducing `figment`. Also, please fix the CI error.

**Comment by Lethe10137** [comment]
> Please use `serde_json` directly for our tests instead of introducing `figment`. Also, please fix the CI error.

I do not use `serde_json` because we have used  `serde_json` to test the deserialization in [current CI](https://github.com/stack-rs/netem-trace/blob/7e818ff30af7be5956b3946565bc28feb1cab10c/src/model/bw.rs#L530-L531
) -- and the current code in main branch passes that!

Consider the following code:

```rust

use netem_trace::model::BwTraceConfig;
use figment::{Figment, providers::{Format, Json}};

fn main() {
    let config = r##"
{
    "RepeatedBwPatternConfig": {
        "pattern": [{"TraceBwConfig": [["25ms",["10Mbps", "20Mbps"]]]}],
        "count": 0
    }
}
    "##;
    let _trace : Box<dyn BwTraceConfig> = serde_json::de::from_str(&config).unwrap();
    let _trace = Figment::new()
        .merge(Json::string(config))
        .extract::<Box<dyn BwTraceConfig>>()
        .map(|_|()).unwrap_err();
}

```

`cargo.toml`
```toml
[package]
name = "use_netem"
version = "0.1.0"
edition = "2021"

[dependencies]
netem-trace = {version = "0.3.5", features = ["serde","human"]}
serde_json = "1.0"
serde = "1.0.152"
figment = {version = "0.10.19", features = ["env", "json","toml"]}
```

It shows that the current code in main branch is compatible with `serde_json` but not `figment`.

[Since rattan uses `figment`](https://github.com/stack-rs/rattan/blob/a6c83950c06fb5c1dd3d753b4449d5c640de1103/rattan-core/src/config/bandwidth.rs#L171-L185), we have to make sure that our (de)serialization is compatible with not only `serde_json` but also `figment`.

As shown in  [21346c3](https://github.com/stack-rs/netem-trace/pull/15/commits/21346c36287cbac6c026ab821bd07193a5f462f8), 
which addes the ci test, current code in main branch is incompatible with `figment`,
and in [c61a1ec](https://github.com/stack-rs/netem-trace/pull/15/commits/c61a1eccb0e3f9ddc1093ee55cff8215fba1fccf), which solved that issue.

**Comment by BobAnkh** [comment]
> It shows that the current code in main branch is compatible with `serde_json` but not `figment`.
> 
> [Since rattan uses `figment`](https://github.com/stack-rs/rattan/blob/a6c83950c06fb5c1dd3d753b4449d5c640de1103/rattan-core/src/config/bandwidth.rs#L171-L185), we have to make sure that our (de)serialization is compatible with not only `serde_json` but also `figment`.
> 
> As shown in [21346c3](https://github.com/stack-rs/netem-trace/pull/15/commits/21346c36287cbac6c026ab821bd07193a5f462f8), which addes the ci test, current code in main branch is incompatible with `figment`, and in [c61a1ec](https://github.com/stack-rs/netem-trace/pull/15/commits/c61a1eccb0e3f9ddc1093ee55cff8215fba1fccf), which solved that issue.

Although Rattan uses `figment`, not `serde_json`, we are just testing the operation of serialization. So, testing with `serde_json` is enough. The reason we chose `serde_json` instead of `figment` is that we are already using it in this project. Also, this is intended to be an individual crate for many purposes, so we shall test its features in a general way. So `serde_json` is more like a good choice. Also, the underlying JSON feature of the figment is, in fact, uses `serde_json` to perform the serialization.

**Comment by BobAnkh** [comment]
Do you mean the code is compatible with `serde_json` but not `figment`? Can you please explain more on the reason why a general serialization code cannot be compatible with `figment`?

```rust

use netem_trace::model::BwTraceConfig;
use figment::{Figment, providers::{Format, Json}};

fn main() {
    let config = r##"
{
    "RepeatedBwPatternConfig": {
        "pattern": [{"TraceBwConfig": [["25ms",["10Mbps", "20Mbps"]]]}],
        "count": 0
    }
}
    "##;
    let _trace : Box<dyn BwTraceConfig> = serde_json::de::from_str(&config).unwrap();
    let _trace = Figment::new()
        .merge(Json::string(config))
        .extract::<Box<dyn BwTraceConfig>>()
        .map(|_|()).unwrap_err();
}
```

**Comment by Lethe10137** [comment]
> Do you mean the code is compatible with `serde_json` but not `figment`? Can you please explain more on the reason why a general serialization code cannot be compatible with `figment`?


I do mean that the code is compatible with `serde_json` but not `figment`. 

From the `Err` given by `figment` as below, I think that it is an issue for `figment`, but not for our code.

```text
... Message("invalid type: found string \"25ms\", expected a borrowed string in JSON source string in JSON source string in JSON source string in JSON source string in JSON source string in JSON source string")...
```
Given that, in the current code of  deserialization of `TraceBwConfig`, we expect a serial of `&str`,
``` rust
while let Some((duration_str, bandwidths_str)) =
                    seq.next_element::<(&str, Vec<&str>)>()?
                {
```

it looks that `serde_json` can convert between `&str` and `String` here, but `figment` fails to do so.

**Comment by BobAnkh** [comment]
Ok, then I'm fine with that.

**Pull request merged**
